name: PHPCS Test
on: [push]
jobs:
  run:
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest', 'windows-latest' ]
        php-versions: [ '7.1', '7.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring, intl
          tools: phpcs
      - name: PHPCS on Linux
        if: matrix.os == 'ubuntu-latest'
          run: |
            phpcs TestCode/*.fixed.php
      - name: PHPCS on Windows
        if: matrix.os == 'windows-latest'
          run: |
            phpcs TestCode\*.fixed.php

